### ISSUE TITLE
Crear Requirement.txt

### ISSUE THREAD

**Issue by Virzlauvinen** [Virzlauvinen/PP2_MODELO#2]

**Comment by Virzlauvinen** [comment]
Las librerías utilizadas las podés encontrar en el archivo PP2_MODELO_DT en el apartado "Librerías". El objetivo es encontrar la version utilizada de cada una en el modelo y dejarlo asentado en el archivo .txt "Requirement"

**Comment by octagomez** [comment]
se utiliza la libreria pipreqs para su actualizacion.
en el archivo readme.md en el root del proyecto esta detallados los pasos que se realizaron.

**Comment by Virzlauvinen** [comment]
Todas las instrucciones quedarán en diferentes Pages de la Wiki
